### ISSUE TITLE
GitHub Workflow yaml is interpreted as Ansible Playbook

### ISSUE THREAD

**Issue by nounderline** [b0o/SchemaStore.nvim#35]
Putting valid GH workflow definition under `.github/workflows/site.yml` renders following error:
```
Incorrect type. Expected "array". yaml-schema: Ansible Playbook (0) [1, 1]
```

Renaming the file fixes the issue and applies "GitHub Workflow" as expected.

This happens because of schema definition for Ansible as defined here:

https://github.com/b0o/SchemaStore.nvim/blob/57116dd9fd9ee4d73c1e9a1335d92b4c71851cf7/lua/schemastore/catalog.lua#L1095-L1098

I think that schemas for files that are nested should be prioritized and override more general ones. So in this case "GitHub Workflow" should take a precedence over "Ansible Playbook"  because its file matching are more fine grainer.

**Comment by b0o** [comment]
There is not much we can do in this plugin, because we are just consuming the catalog from the upstream SchemaStore project and providing it to the LSP. I would recommend opening an issue in the upstream [SchemaStore](https://github.com/SchemaStore/schemastore) repo or with [yaml-language-server](https://github.com/redhat-developer/yaml-language-server/).

**Comment by nounderline** [comment]
@b0o https://github.com/SchemaStore/schemastore/pull/3929 should fix the issue.

**Comment by b0o** [comment]
Nice, it was picked up by our CI already: https://github.com/b0o/SchemaStore.nvim/commit/58a965eedbfe7c358938b0e535ed2d98a4520987

If you update your neovim plugins, you should receive these changes.
